<?php
/*-----------------------------------------------------------------------------------*/
/* Custom Fields */
/*-----------------------------------------------------------------------------------*/

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_student-data',
		'title' => 'Student data',
		'fields' => array (
			array (
				'key' => 'field_56fae37dd17a6',
				'label' => 'Name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => 'This is how your name will appear on your display in the show.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '(eg Paul Rennie)',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 50,
			),
			array (
				'key' => 'field_573f46426e81e',
				'label' => 'Student ID Number',
				'name' => 'student_number',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 11,
			),
			array (
				'key' => 'field_5702d8cda395a',
				'label' => 'Route',
				'name' => 'route',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'null' => '',
					'Design & Interaction' => 'Design & Interaction',
					'Illustration' => 'Illustration',
					'Moving Image' => 'Moving Image',
					'Advertising' => 'Advertising',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_573f46856e81f',
				'label' => 'Link to personal website',
				'name' => 'link_to_personal_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 50,
			),
			array (
				'key' => 'field_56fae44dd17a8',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '(Not UAL email, personal email please)',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '(eg john.appleseed@gmail.com)',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_573f47476e822',
				'label' => 'Social media accounts',
				'name' => 'social_media_accounts',
				'type' => 'checkbox',
				'instructions' => 'Please check which social medias you have an account on.',
				'choices' => array (
					'Twitter' => 'Twitter',
					'Instagram' => 'Instagram',
					'Youtube' => 'Youtube',
					'Vimeo' => 'Vimeo',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5702dc2698acd',
				'label' => 'Twitter',
				'name' => 'twitter',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f47476e822',
							'operator' => '==',
							'value' => 'Twitter',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => '(eg. @stevewoz)',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 50,
			),
			array (
				'key' => 'field_573f47136e820',
				'label' => 'Instagram',
				'name' => 'instagram',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f47476e822',
							'operator' => '==',
							'value' => 'Instagram',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => '(eg. @stevewoz)',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_573f47bf6e823',
				'label' => 'Youtube',
				'name' => 'youtube',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f47476e822',
							'operator' => '==',
							'value' => 'Youtube',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '(eg. https://www.youtube.com/user/Apple)',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_573f47ed6e824',
				'label' => 'Vimeo',
				'name' => 'vimeo',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f47476e822',
							'operator' => '==',
							'value' => 'Vimeo',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '(eg. https://vimeo.com/user24085556)',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_573f490ebbd66',
				'label' => 'Bio',
				'name' => 'bio',
				'type' => 'text',
				'instructions' => 'Please write a bit about yourself. This is meant to be an introduction to you, so perhaps write about your design practice and where you want to take it. This will not be proofread by anyone but you. <br>Typos = No job for you!',
				'required' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '600',
			),
			array (
				'key' => 'field_573ee16a81d30',
				'label' => 'Tags',
				'name' => 'tags',
				'type' => 'select',
				'instructions' => 'Please select a maximum of 7 tags that fits your body work best. Any more than that will be ignored.',
				'choices' => array (
					'Routes' => array(
						'Illustration' => 'Illustration',
						'Advertising' => 'Advertising',
						'Moving Image' => 'Moving Image',
						'Design & Interaction' => 'Design & Interaction'
					),
					'Medium' => array(
						'Editorial' => 'Editorial',
						'Craft' => 'Craft',
						'Photography' => 'Photography',
						'Typography' => 'Typography',
						'Print' => 'Print',
						'Web' => 'Web',
						'Digital Media' => 'Digital Media',
						'Installation' => 'Installation',
					),
					'Voice' => array(
						'Social Design' => 'Social Design',
						'Branding' => 'Branding',
						'Fine Art' => 'Fine Art',
						'Social Media' => 'Social Media',
						'Experiential' => 'Experiential',
						'Identity' => 'Identity',
						'Problem Solving' => 'Problem Solving',
						'Mapping' => 'Mapping',
					),
					'Content' => array(
						'Utopia/Dystopia' => 'Utopia/Dystopia',
						'Culture' => 'Culture',
						'Reality/Fiction' => 'Reality/Fiction',
						'System' => 'System',
						'Chaos/Order' => 'Chaos/Order',
						'Language' => 'Language',
						'Storytelling' => 'Storytelling',
						'Environment' => 'Environment',
						'Technology' => 'Technology',
						'Education' => 'Education',
						'Society' => 'Society',
					),
					'Other' => array(
						'Other' => 'Other'
					)
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_573ee1fb81d31',
				'label' => 'Other:',
				'name' => 'other:',
				'type' => 'text',
				'instructions' => 'Please key in any additional keywords separated by commas ( , )',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573ee16a81d30',
							'operator' => '==',
							'value' => 'Other',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => '(eg Mathematics, Economy, Literature)',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_573f52ef1ae7e',
				'label' => 'Question',
				'name' => 'question',
				'type' => 'radio',
				'instructions' => 'This field is to be filled in by editors only. Please choose the degree show question related to the student in question here.',
				'required' => 0,
				'choices' => array (
					'q1' => 'How does graphic communication (re)solve problems?',
					'q2' => 'How do we find a voice in a commercial world?',
					'q3' => 'How do we (re)design who we are?',
					'q4' => 'Is technology leading us to utopia or dystopia?',
					'q5' => 'How do we (re)materialise culture?',
					'q6' => 'What is wrong with design/society?',
					'q7' => 'How is reality formed by narratives?',
					'q8' => 'Should design impose order or chaos?',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'null',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_573f52ef1ae7b',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'message',
				'message' => '<h3>You can show up to a maximum of 3 images or videos on the website. Please select options below:</h3>',
			),
			array (
				'key' => 'field_573f5193b9d23',
				'label' => 'Hero image/video',
				'name' => 'hero_image_video',
				'type' => 'radio',
				'instructions' => 'This is the image that will appear first, right below your name. We recommend you put an image that represents your project displayed in the Degree Show. This will help users make the connection to what they saw in the show.',
				'required' => 0,
				'choices' => array (
					'Image' => 'Image',
					'Video' => 'Video',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'null',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5702cb8c85d10',
				'label' => 'Hero image',
				'name' => 'hero_image',
				'type' => 'image',
				'required' => 0,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f5193b9d23',
							'operator' => '==',
							'value' => 'Image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_573f5180b9d22',
				'label' => 'Hero video',
				'name' => 'hero_video',
				'type' => 'text',
				'instructions' => 'Please submit a link to your video on Youtube or Vimeo.',
				'required' => 0,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f5193b9d23',
							'operator' => '==',
							'value' => 'Video',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5704194dd27aa',
				'label' => 'Caption for hero image/video',
				'name' => 'caption_hero',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f5193b9d23',
							'operator' => '==',
							'value' => 'Image',
						),
						array (
							'field' => 'field_573f5193b9d23',
							'operator' => '==',
							'value' => 'Video',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 200,
			),
			array (
				'key' => 'field_573f53dbc4a33',
				'label' => 'Supporting Image/video 1',
				'name' => 'image_video_1',
				'type' => 'radio',
				'choices' => array (
					'Image' => 'Image',
					'Video' => 'Video',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'null',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5702d87098844',
				'label' => 'Supporting image 1',
				'name' => 'image_1',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f53dbc4a33',
							'operator' => '==',
							'value' => 'Image',
						),
					),
					'allorany' => 'any',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_573f55250fd95',
				'label' => 'Supporting video 1',
				'name' => 'video_1',
				'type' => 'text',
				'instructions' => 'Please submit a link to your video on Youtube or Vimeo.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f53dbc4a33',
							'operator' => '==',
							'value' => 'Video',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57041ada93869',
				'label' => 'Caption 1',
				'name' => 'caption_1',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f53dbc4a33',
							'operator' => '==',
							'value' => 'Image',
						),
						array (
							'field' => 'field_573f53dbc4a33',
							'operator' => '==',
							'value' => 'Video',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 200,
			),
			array (
				'key' => 'field_573f54e50fd94',
				'label' => 'Supporting Image/video 2',
				'name' => 'image_video_2',
				'type' => 'radio',
				'instructions' => 'This can be another image from the same project, or another project altogether.',
				'choices' => array (
					'Image' => 'Image',
					'Video' => 'Video',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'null',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5702d89498846',
				'label' => 'Supporting image 2',
				'name' => 'image_2',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f54e50fd94',
							'operator' => '==',
							'value' => 'Image',
						),
					),
					'allorany' => 'any',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_573f55580fd96',
				'label' => 'Supporting video 2',
				'name' => 'video_2',
				'type' => 'text',
				'instructions' => 'Please submit a link to your video on Youtube or Vimeo.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f54e50fd94',
							'operator' => '==',
							'value' => 'Video',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57041b379386c',
				'label' => 'Caption 2',
				'name' => 'caption_2',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_573f54e50fd94',
							'operator' => '==',
							'value' => 'Image',
						),
						array (
							'field' => 'field_573f54e50fd94',
							'operator' => '==',
							'value' => 'Video',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 200,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'student_info',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


